
global:
  security:
    allowInsecureImages: true

image:
  repository: redis/redis-stack-server
  tag: 7.4.0-v5

auth:
  enabled: true
  sentinel: true
  password: ReD!$P@$$
  acl:
    enabled: false
    users: []

replica:
  replicaCount: 2
  extraFlags:
    - '--protected-mode no'
  resources:
    requests:
      cpu: '250m'
      memory: '512Mi'
    limits:
      cpu: '1'
      memory: '1Gi'
  podAffinityPreset: ''
  podAntiAffinityPreset: 'soft'
  persistence:
    enabled: true
    size: 1Gi
    storageClass: longhorn
  automountServiceAccountToken: true

  pdb:
    create: false
    minAvailable: ""
    maxUnavailable: ""

# master:
#   replicaCount: 1
#   extraFlags:
#     - '--protected-mode no'
#   resources:
#     requests:
#       cpu: '250m'
#       memory: '512Mi'
#     limits:
#       cpu: '1'
#       memory: '1Gi'
#   podAffinityPreset: ''
#   podAntiAffinityPreset: 'soft'
#   persistence:
#     enabled: true
#     size: 2Gi
#     storageClass: longhorn
#   automountServiceAccountToken: true

#   pdb:
#     create: false
#     minAvailable: ""
#     maxUnavailable: ""

sentinel:
  enabled: true
  masterSet: 'mymaster'
  quorum: 2
  masterService:
    enabled: true
    type: ClusterIP
  resources:
    requests:
      cpu: '250m'
      memory: '512Mi'
    limits:
      cpu: '1'
      memory: '1Gi'

rbac:
  create: true

serviceAccount:
  create: true
  name: 'redis-stack-server-service-account'
  automountServiceAccountToken: true





# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: redis-1
#   namespace: development
# spec:
#   chart:
#     spec:
#       chart: redis
#       sourceRef:
#         kind: HelmRepository
#         name: bitnami
#         namespace: system
#       version: 19.5.0
#   interval: 1m0s
#   install:
#     replace: true
#     remediation:
#       retries: -1
#     disableWait: true
#     disableWaitForJobs: true
#   upgrade:
#     force: true
#     remediation:
#       retries: -1
#     disableWait: true
#     disableWaitForJobs: true
#   values:
#     image:
#       repository: redis/redis-stack-server
#       tag: 7.4.0-v5
#     master:
#       persistence:
#         enabled: true
#         size: 5Gi
#         storageClass: longhorn
#     replica:
#       replicaCount: 3
#       command:
#         - "/opt/redis-stack/bin/redis-server"
#         - "--loadmodule"
#         - "/opt/redis-stack/lib/redisearch.so"
#         - "MAXSEARCHRESULTS"
#         - "10000"
#         - "MAXAGGREGATERESULTS"
#         - "10000"
#         - "--loadmodule"
#         - "/opt/redis-stack/lib/rejson.so"
#       persistence:
#         enabled: true
#         size: 5Gi
#         storageClass: longhorn
#     sentinel:
#       # This will disable the master and replicas services and
#       # create a single Redis service exposing both the Redis and Sentinel ports.
#       enabled: true